### ISSUE TITLE
Code not working?

### ISSUE THREAD

**Issue by nishi7409** [designcourse/angular-auth-demo#5]
Keep on getting this error **even** after I uninstall and install what it asks me to install.
What would the fix be?

![image](https://cloud.githubusercontent.com/assets/20250366/23440266/128c316a-fde9-11e6-8832-1859e35cb337.png)

**Comment by MrExpert** [comment]
code isn't working

**Comment by pba3** [comment]
The code is not working as it suppose to. Any help?
<img width="598" alt="capture" src="https://user-images.githubusercontent.com/22327481/28676385-877d7292-72b8-11e7-93f8-45935c7f2102.PNG">
